### PR TITLE
Added DUAL-LICENSE.md

### PR DESCRIPTION
**Pull request by srbala**
Added short version license file for quick reference

### CODE REVIEW

**Comment by srbala** [comment]
It's great my ECA checks out. I did sign the commit with -S option. Is my public keys needed to be uploaded eclipse server or any other place?

sign-verify

**Comment by m0mus** [comment]
Why do we need another license file? There is everything needed in LICENSE.md file and it's consistent in all EE4J project.

**Comment by keilw** [comment]
+1 despite the name the existing LICENSE.md contains both already. @srbala please advise or maybe close the PR.

**Comment by srbala** [comment]
On first look it gave me the impression that license is EPL. So, I created PR #186 to follow github standard practice. Current license file contains multiple pages long, later only I realized it is dual license and closed that PR.  My current PR gives direct answer. I have seen other projects which follows multiple license has separate files (ex. license-epl and license-gpl) and indication as dual license.

If the team disagrees, I'll close the PR.

**Comment by keilw** [comment]
Maybe something to ask the PMC but as @m0mus represents Oracle there, I trust it was done as desired for all EE4J projects here so far (a few were already EPL only, most others are dual-licensed)

**Comment by srbala** [comment]
Closing PR

**Pull request closed without merging**
