### PR TITLE
Set version to 3.0.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by dblevins**
Don't merge until our final release is approved and published.

### CODE REVIEW

**Comment by pzygielo** [comment]
With 568693 completed and https://repo.maven.apache.org/maven2/jakarta/jms/jakarta.jms-api/3.0.0/ published - can this PR continue?

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
Yes, it should continue indeed.

**Comment by OndroMih** [comment]
The next version should be 3.1.0 because we plan to do some minor API enhancements like repeating annotations as mentioned in the [release plan](https://github.com/jakartaee/specifications/pull/380).

**Comment by arjantijms** [comment]
> The next version should be 3.1.0 

Yes, but for admin reasons we typically merge the release branch into master, so that those branches don't show any missed commits.

But this PR is too troublesome with the failing ECA check, so let's close it.

**Comment by OndroMih** [comment]
I agree, this PR is not in a good shape. The 3.0.0 branch is already up to date with the master branch except the change from 3.0.0-SNAPSHOT to 3.0.1-SNAPSHOT which I think shouldn't even be added to the master branch. The master branch should directly jump to 3.1.0-SNAPSHOT instead.

**Pull request closed without merging**
