### PR TITLE
Convert package from javax to jakarta

### PR DESCRIPTION
**Pull request by Cousjava**

### CODE REVIEW

**Comment by m0mus** [comment]
Fixed #254

**Comment by bshannon** [comment]
This doesn't seem to use the new ee4j parent pom. Did you find that was unnecessary?

**Comment by m0mus** [comment]
It was created before new parent pom was released. Uptaking new parent pom can be done in another PR.

**Comment by arjantijms** [comment]
Should the new version be `3.0-SNAPSHOT` or `3.0.0-SNAPSHOT`?

**Comment by m0mus** [comment]
I guess `3.0-SNAPSHOT`

**Comment by arjantijms** [comment]
I noticed that the Jakarta EE platform spec is 8.0.0 vs 8.0 that Java EE used before, and GlassFish was now asked to move to 6.0.0, hence I wondered if the x.0.0 might be a new recommendation for version numbers.

**Comment by m0mus** [comment]
There were no recommendations from PMC, so IMO no changes is the right approach. If it needs to be discussed please post a question to the PMC mailing list.

**Comment by arjantijms** [comment]
Okay, I'm not particularly in favour of the x.0.0 scheme, but was more wondering whether it was a recommendation or not. Thanks!

**Comment by t1** [comment]
Isn't [semver](https://semver.org) a good versioning scheme also for Jakarta EE? Every version part would have a quite clear message: The Bad, The Good, and The Ugly 😉

**Comment by bshannon** [comment]
@m0mus @arjantijms 
I'm not sure what we're talking about the version of here so let me give the general rule...

Programming artifacts, e.g., jar files full of class files, zip files containing an implementation for download, etc. always have dot-dot version numbers, even when the minor and micro numbers are zero.

Specification documents have single-dot version numbers, with an optional "rev level" indicating an errata update to the document.

So, if you're talking about the API jar file, it should be 3.0.0-SNAPSHOT.

If you're talking about the Jakarta Messaging specification document, it should be 3.0-SNAPSHOT.  If you have to fix a typo after 3.0 is released, the new version would be 3.0-RevA.  (We could argue about the capitalization.)

**Comment by arjantijms** [comment]
> So, if you're talking about the API jar file, it should be 3.0.0-SNAPSHOT

So what you’re saying is that the version in the Pom here should be set to 3.0.0-SNAPSHOT after all?

**Comment by smillidge** [comment]
yes 3.0.0-SNAPSHOT for api jars 3.0 for the spec version

**Comment by bshannon** [comment]
> > So, if you're talking about the API jar file, it should be 3.0.0-SNAPSHOT
> 
> So what you’re saying is that the version in the Pom here should be set to 3.0.0-SNAPSHOT after all?

Yes.  Is that still confusing?  How can I describe this so it's less confusing?

**Comment by arjantijms** [comment]
> Yes. Is that still confusing? How can I describe this so it's less confusing?

No, it's super clear. My OCD kicked in for a moment ;)

**Pull request merged**
