### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ANadrowski**
Fix typo.

### CODE REVIEW

**Comment by ANadrowski** [comment]
Hi @keilw, 
Do you mean ECA (Eclipse Contributor Agreement)? The ECA I've signed.

**Comment by keilw** [comment]
@ANadrowski Yes, but the ip-validation may be related to how you pushed the PR, could you change the "signed-off" and make sure, the email address you used there is identical to the one from your ECA? That is sometimes a known issue and mismatch in the Eclipse system. I don't think we can merge the PR if any of the checks fail.

**Comment by ANadrowski** [comment]
@keilw this is my first PR, so I'm not sure if I doing the right thing.. but I'm sure that the email in the ECA is the same that I used to create the commit:

aislan@aislan:~/Documents/Github/jms-api$ git add README.md 
aislan@aislan:~/Documents/Github/jms-api$ git config user.name "Aislan Nadrowski"
aislan@aislan:~/Documents/Github/jms-api$ git config user.email "aislan.nadrowski@gmail.com"
aislan@aislan:~/Documents/Github/jms-api$ git commit -m "Fix typo"

Do you see something wrong here?

Thank you.

**Comment by keilw** [comment]
It seems the commit chain does not contain the `signed-off-by` line, that is what Eclipse servers complain about here.

**Comment by ANadrowski** [comment]
@keilw so the right thing now is to close this PR and then I should create a new PR with the `signed-off-by` included?

Thanks.

**Comment by keilw** [comment]
As it is just a small change, please do if you can.

**Pull request closed without merging**
